config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: %i[ new create destroy ]
  resources :users, except: :index
  resources :tasks, only: %i[ index create update destroy ]
  root to: "sessions#new"
  resources :memos, only: %i[ index create update destroy ]
  resources :blogs, only: %i[ index create update destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  validates :content, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

  def index
    @memos = Memo.order(id: :desc)
  end

  def create
    @memo = Memo.new(params.require(:memo).permit(:content))
    @memos = Memo.order(id: :desc)
    redirect_to memos_path, notice: "新規メモ#{@memo.content}作成" and return if @memo.save
    render :index, status: :unprocessable_entity
  end

  def update
    @memo = Memo.find(params[:id])
    content = @memo.content
    @memos = Memo.order(id: :desc)
    redirect_to memos_path, notice: "#{content}から#{@memo.content}へ更新" and return if @memo.update(params.require(:memo).permit(:id, :content))
    render :index, status: :unprocessable_entity
  end

  def destroy
    @memo = Memo.find(params[:id])
    content = @memo.content
    @memo.destroy
    redirect_to memos_path, notice: "#{content}を削除"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    def new
    end

    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to user_path(user.id)
      else
        flash[:danger] = 'ログインに失敗しました'
        render :new
      end
    end

    def destroy
      session.delete(:user_id)
      flash[:notice] = 'ログアウトしました'
      redirect_to new_session_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @task = Task.new
    @tasks = Task.all
  end

  def create
    @task = Task.new(params.require(:task).permit(:title))
    respond_to do |format|
      format.json { render index: @task, status: :created} and return if @task.save
      format.json { render json: @task.errors, status: :unprocessable_entity }
    end
  end

  def update
    @task = Task.find(params[:id])
    respond_to do |format|
      format.json { render index: @task, status: :created } and return if @task.update(params.require(:task).permit(:id, :title))
      format.json { render json: @task.errors, status: :unprocessable_entity }
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    render :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :login_required, only: [:new, :create]

  def index
    @users = User.all
  end

  def show
    binding.irb
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    session[:user_id] = user.id
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VuePractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header"><header-component></header-component></div>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
    <div id="footer"><footer-component></footer-component></div>
    <%= javascript_pack_tag 'header_vue' %>
    <%= javascript_pack_tag 'footer_vue' %>
    <%= javascript_pack_tag 'task_vue' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/memos/_error_message.html.erb
<% if memo.errors.any? %>
  <div id="error_explanation d-flex flex-column align-items-center">
    <ul style="margin: 0;">
      <% memo.errors.full_messages.each do |message| %>
        <%= content_tag :li, "error : #{message} !", style: "width: 300px; line-height: 30px; color: red; list-style: none; font-size: 20px" %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/memos/index.html.erb
<h1>Memos</h1>

<%= form_with(model: Memo.new, local: true) do |form| %>
  <div class="d-flex flex-row align-items-center">
    <div class="d-flex flex-row">
      <div class="field", style="margin-right: 20px; padding-top: 5px;">
        <%= form.label :content %>
        <%= form.text_field :content %>
      </div>

      <div class="actions">
        <%= form.submit "送信", class: "btn btn-info" %>
      </div>
    </div>
    <br>
    <% if @memo && @memo.id == nil %>
      <%= render 'error_message', memo: @memo%>
    <% end %>
  </div>
<% end %>

<br>
<p id="notice" style="color: green; font-size: 20px;"><%= notice %></p>
<br>

<table>
  <thead>
    <tr>
      <th style="padding: 0 20px 0 20px;">Content</th>
      <th>edit_form</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td style="padding: 0 20px;"><%= memo.content %></td>
        <%= form_with(model: memo, local: true, url: memo_path(memo.id), method: :patch) do |f| %>
          <td><%= f.text_field :content, value: memo.content, style: "margin-right: 20px;" %></td>
          <td><%= f.submit 'update', class: "btn btn-outline-secondary", style: "margin-right: 10px;" %></td>
          <td><%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-info" %></td>
          <td>
            <% if @memo && @memo.id == memo.id %>
              <%= render 'error_message', memo: @memo %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tasks/index.html.erb
<h1>Task</h1>
<br>
<div id="app"><task-component /></div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirm %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>